#!/usr/bin/env bash

# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

#
# When you click an icon in the launcher, it opens the application. You click the icon again and nothing happens.
#
# I don’t like this. I prefer that when I click on the icon of an application in focus, it gets minimized.
#
# Source: https://itsfoss.com/things-to-do-after-installing-ubuntu-22-04/
#
# And then https://github.com/micheleg/dash-to-dock/blob/master/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
#
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize-or-previews'

#
# Keyboard Shortcuts - Bindings
#
"${MYDIR}"/bindings/load_bindings
