#!env /bin/zsh

# http://unix.stackexchange.com/questions/76505/portable-way-to-get-scripts-absolute-path
MYDIR=${0:a:h}

# echo $MYDIR

ANTIGEN_LOCATION=~

# echo $ANTIGEN_LOCATION
git clone git@github.com:zsh-users/antigen.git $ANTIGEN_LOCATION/antigen

mkdir ~/go

echo "Linking .zshrc"
ln -s $MYDIR/zsh/zshrc ~/.zshrc
