#!/usr/bin/env bash

# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
# echo ${DIR}

mkdir -p ~/.local/bin

for binfile in "${MYDIR}"/bin/*; do
	name="$(basename "${binfile}")"
	target="${HOME}/.local/bin/${name}"
	echo "Linking ${binfile} if not there"
	if [[ ! -e "${target}" ]]; then
		ln -s "${binfile}" "${target}"
	fi
done
