#!/usr/bin/env bash

#
# Follow up:
# Add :
# 	https://extensions.gnome.org/extension/2890/tray-icons-reloaded/
# 	https://github.com/martinpl/tray-icons-reloaded
#

#
# Install Burn My Windows
#
gext install burn-my-windows@schneegans.github.com
gnome-extensions enable burn-my-windows@schneegans.github.com

#
# Copy gsettings schemas so that they can be set from command line:
#
sudo cp ~/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/schemas/org.gnome.shell.extensions.burn-my-windows.gschema.xml /usr/share/glib-2.0/schemas/
sudo cp ~/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/schemas/org.gnome.shell.extensions.burn-my-windows-profile.gschema.xml /usr/share/glib-2.0/schemas/

#
# Recompile
#
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/

#
# Set values with my preferences
#
gsettings set org.gnome.shell.extensions.burn-my-windows-profile apparition-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile aura-glow-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile broken-glass-animation-time 1000
gsettings set org.gnome.shell.extensions.burn-my-windows-profile broken-glass-blow-force 0.5
gsettings set org.gnome.shell.extensions.burn-my-windows-profile broken-glass-enable-effect true
gsettings set org.gnome.shell.extensions.burn-my-windows-profile broken-glass-gravity -1.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile broken-glass-scale 1.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile broken-glass-use-pointer false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile doom-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile energize-a-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile energize-b-animation-time 1000
gsettings set org.gnome.shell.extensions.burn-my-windows-profile energize-b-color 'rgb(160, 180, 255)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile energize-b-enable-effect true
gsettings set org.gnome.shell.extensions.burn-my-windows-profile energize-b-scale 1.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-3d-noise false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-animation-time 1500
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-color-1 'rgba(76, 51, 25, 0.0)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-color-2 'rgba(180, 55, 30, 0.7)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-color-3 'rgba(255, 76, 38, 0.9)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-color-4 'rgba(255, 166, 25, 1)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-color-5 'rgba(255, 255, 255, 1)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-enable-effect true
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-movement-speed 0.5
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-random-color false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile fire-scale 1.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile focus-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile glide-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile glitch-animation-time 750
gsettings set org.gnome.shell.extensions.burn-my-windows-profile glitch-color 'rgb(100, 160, 255)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile glitch-enable-effect true
gsettings set org.gnome.shell.extensions.burn-my-windows-profile glitch-scale 1.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile glitch-speed 2.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile glitch-strength 2.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile hexagon-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile incinerate-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile matrix-animation-time 1500
gsettings set org.gnome.shell.extensions.burn-my-windows-profile matrix-enable-effect true
gsettings set org.gnome.shell.extensions.burn-my-windows-profile matrix-overshoot 0.25
gsettings set org.gnome.shell.extensions.burn-my-windows-profile matrix-randomness 1.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile matrix-scale 20
gsettings set org.gnome.shell.extensions.burn-my-windows-profile matrix-tip-color 'rgb(255, 255, 255)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile matrix-trail-color 'rgb(25, 255, 89)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile mushroom-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile paint-brush-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile pixel-wheel-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile pixel-wipe-animation-time 1000
gsettings set org.gnome.shell.extensions.burn-my-windows-profile pixel-wipe-enable-effect true
gsettings set org.gnome.shell.extensions.burn-my-windows-profile pixel-wipe-pixel-size 10
gsettings set org.gnome.shell.extensions.burn-my-windows-profile pixelate-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile portal-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile profile-animation-type 0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile profile-app ''
gsettings set org.gnome.shell.extensions.burn-my-windows-profile profile-color-scheme 0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile profile-high-priority false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile profile-power-mode 0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile profile-power-profile 0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile profile-window-type 0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile rgbwarp-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile snap-animation-time 1500
gsettings set org.gnome.shell.extensions.burn-my-windows-profile snap-color 'rgb(50, 40, 35)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile snap-enable-effect true
gsettings set org.gnome.shell.extensions.burn-my-windows-profile snap-scale 3.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile team-rocket-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile trex-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile tv-enable-effect false
gsettings set org.gnome.shell.extensions.burn-my-windows-profile tv-glitch-animation-time 750
gsettings set org.gnome.shell.extensions.burn-my-windows-profile tv-glitch-color 'rgb(100, 160, 255)'
gsettings set org.gnome.shell.extensions.burn-my-windows-profile tv-glitch-enable-effect true
gsettings set org.gnome.shell.extensions.burn-my-windows-profile tv-glitch-scale 1.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile tv-glitch-speed 2.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile tv-glitch-strength 2.0
gsettings set org.gnome.shell.extensions.burn-my-windows-profile wisps-enable-effect false
