#!/usr/bin/env bash

#
# Can load with:
# dconf load '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/' < custom_keybindings.conf
#

dconf dump '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/' > custom_keybindings.conf
