#!env /usr/bin/fish
set current_dir (dirname (status --current-filename))
# echo {$current_dir}/dd

echo "Linking fish shell's .config"
ln -s {$current_dir}/config.fish ~/.config/fish/config.fish

echo "Linking fish shell's functions"
ln -s {$current_dir}/functions ~/.config/fish/functions

